### ISSUE TITLE
[Java] Spotless not working with java 8

### ISSUE THREAD

**Issue by nandakumar131** [apache/incubator-fury#1278] opened 2023-12-29 04:54 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

Git commit id: 26f1fc398249d6c7f663e4ba92a83e086cdf9677

### Component(s)

Java

### Minimal reproduce step

- Set Java Home to point to Java 1.8
- Run `mvn spotless:apply`

### What did you expect to see?

`mvn spotless:apply` should reformat the code if required.

### What did you see instead?

The command fails with the following error
```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.41.1:apply (default-cli) on project fury-parent: Execution default-cli of goal com.diffplug.spotless:spotless-maven-plugin:2.41.1:apply failed: Unable to load the mojo 'apply' in the plugin 'com.diffplug.spotless:spotless-maven-plugin:2.41.1' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/diffplug/spotless/maven/SpotlessApplyMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.diffplug.spotless:spotless-maven-plugin:2.41.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment] 2023-12-29 06:04
This is intended. Spotless is dev dependency only. You can use a newer JDK and the produced bytecode is still compatible with JDK 8

**Comment by chaokunyang** [comment] 2023-12-29 07:15
google-java-format need to use a newer JDK to format java `record` class, we can't do it using java8

**Comment by tisonkun** [comment] 2023-12-29 07:17
Closed as answer and not a bug.

**Closed by tisonkun** 2023-12-29 07:17 UTC
Labels: bug
